name: najot_coding
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/Abdirakhmonov/package-coding

environment:
  sdk: ^3.4.2

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.1
  pointycastle: ^3.4.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0


