name: najot_coding
description: "A Dart package for encryption and decryption using AES with customizable key and IV management."
version: 1.0.1
repository: https://github.com/Abdirakhmonov/package-coding
homepage: https://github.com/Abdirakhmonov/package-coding

environment:
  sdk: ^3.4.2

dependencies:
  crypto: ^3.0.1
  pointycastle: ^3.4.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

license: MIT
